version: '3.8'

services:
  # Redis for integration tests
  redis:
    image: redis:7-alpine
    container_name: sage-test-redis
    ports:
      - "6381:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - sage-test

  # PostgreSQL for integration tests
  postgres:
    image: postgres:16-alpine
    container_name: sage-test-postgres
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres
      POSTGRES_DB: sage_test
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - sage-test

networks:
  sage-test:
    driver: bridge
