# SAGE ADK Test Configuration
agent:
  name: "test-agent"
  description: "A simple test agent"
  version: "1.0.0"

server:
  host: "0.0.0.0"
  port: 8080

protocol:
  mode: "a2a"

a2a:
  enabled: true
  version: "0.2.2"
  timeout: 30

storage:
  type: "memory"

logging:
  level: "info"
  format: "json"
