global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'sage-adk-local'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load alert rules
rule_files:
  - '/etc/prometheus/alert-rules.yml'

# Scrape configurations
scrape_configs:
  # SAGE ADK Agent metrics
  - job_name: 'sage-agent'
    static_configs:
      - targets: ['sage-agent:8080']
        labels:
          service: 'sage-adk-agent'
          instance: 'agent-1'
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis metrics (if redis-exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
