// Copyright (C) 2025 sage-x-project
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

// SPDX-License-Identifier: LGPL-3.0-or-later

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageRole represents the role of the message sender
type MessageRole int32

const (
	MessageRole_MESSAGE_ROLE_UNSPECIFIED MessageRole = 0
	MessageRole_MESSAGE_ROLE_USER        MessageRole = 1
	MessageRole_MESSAGE_ROLE_AGENT       MessageRole = 2
	MessageRole_MESSAGE_ROLE_SYSTEM      MessageRole = 3
)

// Enum value maps for MessageRole.
var (
	MessageRole_name = map[int32]string{
		0: "MESSAGE_ROLE_UNSPECIFIED",
		1: "MESSAGE_ROLE_USER",
		2: "MESSAGE_ROLE_AGENT",
		3: "MESSAGE_ROLE_SYSTEM",
	}
	MessageRole_value = map[string]int32{
		"MESSAGE_ROLE_UNSPECIFIED": 0,
		"MESSAGE_ROLE_USER":        1,
		"MESSAGE_ROLE_AGENT":       2,
		"MESSAGE_ROLE_SYSTEM":      3,
	}
)

func (x MessageRole) Enum() *MessageRole {
	p := new(MessageRole)
	*p = x
	return p
}

func (x MessageRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageRole) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (MessageRole) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x MessageRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageRole.Descriptor instead.
func (MessageRole) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

// PartKind represents the type of message part
type PartKind int32

const (
	PartKind_PART_KIND_UNSPECIFIED PartKind = 0
	PartKind_PART_KIND_TEXT        PartKind = 1
	PartKind_PART_KIND_FILE        PartKind = 2
	PartKind_PART_KIND_DATA        PartKind = 3
)

// Enum value maps for PartKind.
var (
	PartKind_name = map[int32]string{
		0: "PART_KIND_UNSPECIFIED",
		1: "PART_KIND_TEXT",
		2: "PART_KIND_FILE",
		3: "PART_KIND_DATA",
	}
	PartKind_value = map[string]int32{
		"PART_KIND_UNSPECIFIED": 0,
		"PART_KIND_TEXT":        1,
		"PART_KIND_FILE":        2,
		"PART_KIND_DATA":        3,
	}
)

func (x PartKind) Enum() *PartKind {
	p := new(PartKind)
	*p = x
	return p
}

func (x PartKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PartKind) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[1].Descriptor()
}

func (PartKind) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[1]
}

func (x PartKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PartKind.Descriptor instead.
func (PartKind) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

type StreamControl_ControlType int32

const (
	StreamControl_CONTROL_TYPE_UNSPECIFIED StreamControl_ControlType = 0
	StreamControl_CONTROL_TYPE_PING        StreamControl_ControlType = 1
	StreamControl_CONTROL_TYPE_CLOSE       StreamControl_ControlType = 2
)

// Enum value maps for StreamControl_ControlType.
var (
	StreamControl_ControlType_name = map[int32]string{
		0: "CONTROL_TYPE_UNSPECIFIED",
		1: "CONTROL_TYPE_PING",
		2: "CONTROL_TYPE_CLOSE",
	}
	StreamControl_ControlType_value = map[string]int32{
		"CONTROL_TYPE_UNSPECIFIED": 0,
		"CONTROL_TYPE_PING":        1,
		"CONTROL_TYPE_CLOSE":       2,
	}
)

func (x StreamControl_ControlType) Enum() *StreamControl_ControlType {
	p := new(StreamControl_ControlType)
	*p = x
	return p
}

func (x StreamControl_ControlType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamControl_ControlType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[2].Descriptor()
}

func (StreamControl_ControlType) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[2]
}

func (x StreamControl_ControlType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamControl_ControlType.Descriptor instead.
func (StreamControl_ControlType) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11, 0}
}

type StreamStatus_StatusType int32

const (
	StreamStatus_STATUS_TYPE_UNSPECIFIED StreamStatus_StatusType = 0
	StreamStatus_STATUS_TYPE_PONG        StreamStatus_StatusType = 1
	StreamStatus_STATUS_TYPE_CLOSED      StreamStatus_StatusType = 2
	StreamStatus_STATUS_TYPE_ERROR       StreamStatus_StatusType = 3
)

// Enum value maps for StreamStatus_StatusType.
var (
	StreamStatus_StatusType_name = map[int32]string{
		0: "STATUS_TYPE_UNSPECIFIED",
		1: "STATUS_TYPE_PONG",
		2: "STATUS_TYPE_CLOSED",
		3: "STATUS_TYPE_ERROR",
	}
	StreamStatus_StatusType_value = map[string]int32{
		"STATUS_TYPE_UNSPECIFIED": 0,
		"STATUS_TYPE_PONG":        1,
		"STATUS_TYPE_CLOSED":      2,
		"STATUS_TYPE_ERROR":       3,
	}
)

func (x StreamStatus_StatusType) Enum() *StreamStatus_StatusType {
	p := new(StreamStatus_StatusType)
	*p = x
	return p
}

func (x StreamStatus_StatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamStatus_StatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[3].Descriptor()
}

func (StreamStatus_StatusType) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[3]
}

func (x StreamStatus_StatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamStatus_StatusType.Descriptor instead.
func (StreamStatus_StatusType) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13, 0}
}

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_SERVING_STATUS_UNKNOWN         HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING_STATUS_SERVING         HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_SERVING_STATUS_NOT_SERVING     HealthCheckResponse_ServingStatus = 2
	HealthCheckResponse_SERVING_STATUS_SERVICE_UNKNOWN HealthCheckResponse_ServingStatus = 3
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "SERVING_STATUS_UNKNOWN",
		1: "SERVING_STATUS_SERVING",
		2: "SERVING_STATUS_NOT_SERVING",
		3: "SERVING_STATUS_SERVICE_UNKNOWN",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"SERVING_STATUS_UNKNOWN":         0,
		"SERVING_STATUS_SERVING":         1,
		"SERVING_STATUS_NOT_SERVING":     2,
		"SERVING_STATUS_SERVICE_UNKNOWN": 3,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[4].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[4]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18, 0}
}

// TextPart represents a text segment in a message
type TextPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextPart) Reset() {
	*x = TextPart{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextPart) ProtoMessage() {}

func (x *TextPart) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextPart.ProtoReflect.Descriptor instead.
func (*TextPart) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *TextPart) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TextPart) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextPart) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// FileContent represents file data (bytes or URI)
type FileContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*FileContent_Bytes
	//	*FileContent_Uri
	Content       isFileContent_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileContent) Reset() {
	*x = FileContent{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileContent) ProtoMessage() {}

func (x *FileContent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileContent.ProtoReflect.Descriptor instead.
func (*FileContent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *FileContent) GetContent() isFileContent_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileContent) GetBytes() *FileWithBytes {
	if x != nil {
		if x, ok := x.Content.(*FileContent_Bytes); ok {
			return x.Bytes
		}
	}
	return nil
}

func (x *FileContent) GetUri() *FileWithURI {
	if x != nil {
		if x, ok := x.Content.(*FileContent_Uri); ok {
			return x.Uri
		}
	}
	return nil
}

type isFileContent_Content interface {
	isFileContent_Content()
}

type FileContent_Bytes struct {
	Bytes *FileWithBytes `protobuf:"bytes,1,opt,name=bytes,proto3,oneof"`
}

type FileContent_Uri struct {
	Uri *FileWithURI `protobuf:"bytes,2,opt,name=uri,proto3,oneof"`
}

func (*FileContent_Bytes) isFileContent_Content() {}

func (*FileContent_Uri) isFileContent_Content() {}

// FileWithBytes represents file data with embedded content
type FileWithBytes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Bytes         []byte                 `protobuf:"bytes,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileWithBytes) Reset() {
	*x = FileWithBytes{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileWithBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWithBytes) ProtoMessage() {}

func (x *FileWithBytes) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileWithBytes.ProtoReflect.Descriptor instead.
func (*FileWithBytes) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *FileWithBytes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileWithBytes) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileWithBytes) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

// FileWithURI represents file data with URI reference
type FileWithURI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Uri           string                 `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileWithURI) Reset() {
	*x = FileWithURI{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileWithURI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWithURI) ProtoMessage() {}

func (x *FileWithURI) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileWithURI.ProtoReflect.Descriptor instead.
func (*FileWithURI) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *FileWithURI) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileWithURI) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileWithURI) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

// FilePart represents a file included in a message
type FilePart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	File          *FileContent           `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePart) Reset() {
	*x = FilePart{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePart) ProtoMessage() {}

func (x *FilePart) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePart.ProtoReflect.Descriptor instead.
func (*FilePart) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *FilePart) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *FilePart) GetFile() *FileContent {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *FilePart) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// DataPart represents arbitrary structured data
type DataPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPart) Reset() {
	*x = DataPart{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPart) ProtoMessage() {}

func (x *DataPart) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPart.ProtoReflect.Descriptor instead.
func (*DataPart) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *DataPart) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DataPart) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataPart) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Part represents a message part (text, file, or data)
type Part struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Part:
	//
	//	*Part_Text
	//	*Part_File
	//	*Part_Data
	Part          isPart_Part `protobuf_oneof:"part"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Part) Reset() {
	*x = Part{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *Part) GetPart() isPart_Part {
	if x != nil {
		return x.Part
	}
	return nil
}

func (x *Part) GetText() *TextPart {
	if x != nil {
		if x, ok := x.Part.(*Part_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *Part) GetFile() *FilePart {
	if x != nil {
		if x, ok := x.Part.(*Part_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *Part) GetData() *DataPart {
	if x != nil {
		if x, ok := x.Part.(*Part_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isPart_Part interface {
	isPart_Part()
}

type Part_Text struct {
	Text *TextPart `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type Part_File struct {
	File *FilePart `protobuf:"bytes,2,opt,name=file,proto3,oneof"`
}

type Part_Data struct {
	Data *DataPart `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

func (*Part_Text) isPart_Part() {}

func (*Part_File) isPart_Part() {}

func (*Part_Data) isPart_Part() {}

// Message represents a single message exchange
type Message struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ContextId string                 `protobuf:"bytes,2,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	Role      MessageRole            `protobuf:"varint,3,opt,name=role,proto3,enum=sage.adk.v1.MessageRole" json:"role,omitempty"`
	Parts     []*Part                `protobuf:"bytes,4,rep,name=parts,proto3" json:"parts,omitempty"`
	Kind      string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata  *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// A2A optional fields
	TaskId           string   `protobuf:"bytes,7,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ReferenceTaskIds []string `protobuf:"bytes,8,rep,name=reference_task_ids,json=referenceTaskIds,proto3" json:"reference_task_ids,omitempty"`
	Extensions       []string `protobuf:"bytes,9,rep,name=extensions,proto3" json:"extensions,omitempty"`
	// Timestamps
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *Message) GetRole() MessageRole {
	if x != nil {
		return x.Role
	}
	return MessageRole_MESSAGE_ROLE_UNSPECIFIED
}

func (x *Message) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *Message) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Message) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Message) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Message) GetReferenceTaskIds() []string {
	if x != nil {
		return x.ReferenceTaskIds
	}
	return nil
}

func (x *Message) GetExtensions() []string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// SendMessageRequest for sending a message to the agent
type SendMessageRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Message *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Request options
	TimeoutSeconds int32 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Stream         bool  `protobuf:"varint,3,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *SendMessageRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SendMessageRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *SendMessageRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

// SendMessageResponse from the agent
type SendMessageResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Message *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Response metadata
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ProcessedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *SendMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SendMessageResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *SendMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SendMessageResponse) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

// StreamMessageRequest for streaming communication
type StreamMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*StreamMessageRequest_Message
	//	*StreamMessageRequest_Control
	Request       isStreamMessageRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessageRequest) Reset() {
	*x = StreamMessageRequest{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessageRequest) ProtoMessage() {}

func (x *StreamMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessageRequest.ProtoReflect.Descriptor instead.
func (*StreamMessageRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *StreamMessageRequest) GetRequest() isStreamMessageRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *StreamMessageRequest) GetMessage() *Message {
	if x != nil {
		if x, ok := x.Request.(*StreamMessageRequest_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *StreamMessageRequest) GetControl() *StreamControl {
	if x != nil {
		if x, ok := x.Request.(*StreamMessageRequest_Control); ok {
			return x.Control
		}
	}
	return nil
}

type isStreamMessageRequest_Request interface {
	isStreamMessageRequest_Request()
}

type StreamMessageRequest_Message struct {
	Message *Message `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type StreamMessageRequest_Control struct {
	Control *StreamControl `protobuf:"bytes,2,opt,name=control,proto3,oneof"`
}

func (*StreamMessageRequest_Message) isStreamMessageRequest_Request() {}

func (*StreamMessageRequest_Control) isStreamMessageRequest_Request() {}

// StreamControl for controlling the stream
type StreamControl struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Type          StreamControl_ControlType `protobuf:"varint,1,opt,name=type,proto3,enum=sage.adk.v1.StreamControl_ControlType" json:"type,omitempty"`
	Data          *structpb.Struct          `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamControl) Reset() {
	*x = StreamControl{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamControl) ProtoMessage() {}

func (x *StreamControl) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamControl.ProtoReflect.Descriptor instead.
func (*StreamControl) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *StreamControl) GetType() StreamControl_ControlType {
	if x != nil {
		return x.Type
	}
	return StreamControl_CONTROL_TYPE_UNSPECIFIED
}

func (x *StreamControl) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

// StreamMessageResponse from streaming
type StreamMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*StreamMessageResponse_Message
	//	*StreamMessageResponse_Status
	Response      isStreamMessageResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessageResponse) Reset() {
	*x = StreamMessageResponse{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessageResponse) ProtoMessage() {}

func (x *StreamMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessageResponse.ProtoReflect.Descriptor instead.
func (*StreamMessageResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *StreamMessageResponse) GetResponse() isStreamMessageResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *StreamMessageResponse) GetMessage() *Message {
	if x != nil {
		if x, ok := x.Response.(*StreamMessageResponse_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *StreamMessageResponse) GetStatus() *StreamStatus {
	if x != nil {
		if x, ok := x.Response.(*StreamMessageResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

type isStreamMessageResponse_Response interface {
	isStreamMessageResponse_Response()
}

type StreamMessageResponse_Message struct {
	Message *Message `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type StreamMessageResponse_Status struct {
	Status *StreamStatus `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

func (*StreamMessageResponse_Message) isStreamMessageResponse_Response() {}

func (*StreamMessageResponse_Status) isStreamMessageResponse_Response() {}

// StreamStatus for stream state information
type StreamStatus struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Type          StreamStatus_StatusType `protobuf:"varint,1,opt,name=type,proto3,enum=sage.adk.v1.StreamStatus_StatusType" json:"type,omitempty"`
	Message       string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp  `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStatus) Reset() {
	*x = StreamStatus{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStatus) ProtoMessage() {}

func (x *StreamStatus) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStatus.ProtoReflect.Descriptor instead.
func (*StreamStatus) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *StreamStatus) GetType() StreamStatus_StatusType {
	if x != nil {
		return x.Type
	}
	return StreamStatus_STATUS_TYPE_UNSPECIFIED
}

func (x *StreamStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StreamStatus) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// GetAgentInfoRequest to retrieve agent information
type GetAgentInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentInfoRequest) Reset() {
	*x = GetAgentInfoRequest{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentInfoRequest) ProtoMessage() {}

func (x *GetAgentInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentInfoRequest.ProtoReflect.Descriptor instead.
func (*GetAgentInfoRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

// GetAgentInfoResponse with agent information
type GetAgentInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentCard     *AgentCard             `protobuf:"bytes,1,opt,name=agent_card,json=agentCard,proto3" json:"agent_card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentInfoResponse) Reset() {
	*x = GetAgentInfoResponse{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentInfoResponse) ProtoMessage() {}

func (x *GetAgentInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentInfoResponse.ProtoReflect.Descriptor instead.
func (*GetAgentInfoResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *GetAgentInfoResponse) GetAgentCard() *AgentCard {
	if x != nil {
		return x.AgentCard
	}
	return nil
}

// AgentCard represents agent metadata
type AgentCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Protocols     []string               `protobuf:"bytes,5,rep,name=protocols,proto3" json:"protocols,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCard) Reset() {
	*x = AgentCard{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCard) ProtoMessage() {}

func (x *AgentCard) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCard.ProtoReflect.Descriptor instead.
func (*AgentCard) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *AgentCard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentCard) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentCard) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentCard) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentCard) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *AgentCard) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// HealthCheckRequest to check agent health
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// HealthCheckResponse with health status
type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=sage.adk.v1.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	Message       string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CheckedAt     *timestamppb.Timestamp            `protobuf:"bytes,3,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_SERVING_STATUS_UNKNOWN
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\vsage.adk.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"g\n" +
	"\bTextPart\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"z\n" +
	"\vFileContent\x122\n" +
	"\x05bytes\x18\x01 \x01(\v2\x1a.sage.adk.v1.FileWithBytesH\x00R\x05bytes\x12,\n" +
	"\x03uri\x18\x02 \x01(\v2\x18.sage.adk.v1.FileWithURIH\x00R\x03uriB\t\n" +
	"\acontent\"V\n" +
	"\rFileWithBytes\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\fR\x05bytes\"P\n" +
	"\vFileWithURI\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\"\x81\x01\n" +
	"\bFilePart\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12,\n" +
	"\x04file\x18\x02 \x01(\v2\x18.sage.adk.v1.FileContentR\x04file\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\x80\x01\n" +
	"\bDataPart\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\x95\x01\n" +
	"\x04Part\x12+\n" +
	"\x04text\x18\x01 \x01(\v2\x15.sage.adk.v1.TextPartH\x00R\x04text\x12+\n" +
	"\x04file\x18\x02 \x01(\v2\x15.sage.adk.v1.FilePartH\x00R\x04file\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x15.sage.adk.v1.DataPartH\x00R\x04dataB\x06\n" +
	"\x04part\"\xc4\x03\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1d\n" +
	"\n" +
	"context_id\x18\x02 \x01(\tR\tcontextId\x12,\n" +
	"\x04role\x18\x03 \x01(\x0e2\x18.sage.adk.v1.MessageRoleR\x04role\x12'\n" +
	"\x05parts\x18\x04 \x03(\v2\x11.sage.adk.v1.PartR\x05parts\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x17\n" +
	"\atask_id\x18\a \x01(\tR\x06taskId\x12,\n" +
	"\x12reference_task_ids\x18\b \x03(\tR\x10referenceTaskIds\x12\x1e\n" +
	"\n" +
	"extensions\x18\t \x03(\tR\n" +
	"extensions\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x85\x01\n" +
	"\x12SendMessageRequest\x12.\n" +
	"\amessage\x18\x01 \x01(\v2\x14.sage.adk.v1.MessageR\amessage\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\x12\x16\n" +
	"\x06stream\x18\x03 \x01(\bR\x06stream\"\xbb\x01\n" +
	"\x13SendMessageResponse\x12.\n" +
	"\amessage\x18\x01 \x01(\v2\x14.sage.adk.v1.MessageR\amessage\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12=\n" +
	"\fprocessed_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\"\x8b\x01\n" +
	"\x14StreamMessageRequest\x120\n" +
	"\amessage\x18\x01 \x01(\v2\x14.sage.adk.v1.MessageH\x00R\amessage\x126\n" +
	"\acontrol\x18\x02 \x01(\v2\x1a.sage.adk.v1.StreamControlH\x00R\acontrolB\t\n" +
	"\arequest\"\xd4\x01\n" +
	"\rStreamControl\x12:\n" +
	"\x04type\x18\x01 \x01(\x0e2&.sage.adk.v1.StreamControl.ControlTypeR\x04type\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\"Z\n" +
	"\vControlType\x12\x1c\n" +
	"\x18CONTROL_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CONTROL_TYPE_PING\x10\x01\x12\x16\n" +
	"\x12CONTROL_TYPE_CLOSE\x10\x02\"\x8a\x01\n" +
	"\x15StreamMessageResponse\x120\n" +
	"\amessage\x18\x01 \x01(\v2\x14.sage.adk.v1.MessageH\x00R\amessage\x123\n" +
	"\x06status\x18\x02 \x01(\v2\x19.sage.adk.v1.StreamStatusH\x00R\x06statusB\n" +
	"\n" +
	"\bresponse\"\x8c\x02\n" +
	"\fStreamStatus\x128\n" +
	"\x04type\x18\x01 \x01(\x0e2$.sage.adk.v1.StreamStatus.StatusTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"n\n" +
	"\n" +
	"StatusType\x12\x1b\n" +
	"\x17STATUS_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10STATUS_TYPE_PONG\x10\x01\x12\x16\n" +
	"\x12STATUS_TYPE_CLOSED\x10\x02\x12\x15\n" +
	"\x11STATUS_TYPE_ERROR\x10\x03\"\x15\n" +
	"\x13GetAgentInfoRequest\"M\n" +
	"\x14GetAgentInfoResponse\x125\n" +
	"\n" +
	"agent_card\x18\x01 \x01(\v2\x16.sage.adk.v1.AgentCardR\tagentCard\"\xd2\x01\n" +
	"\tAgentCard\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12\x1c\n" +
	"\tprotocols\x18\x05 \x03(\tR\tprotocols\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xc0\x02\n" +
	"\x13HealthCheckResponse\x12F\n" +
	"\x06status\x18\x01 \x01(\x0e2..sage.adk.v1.HealthCheckResponse.ServingStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\n" +
	"checked_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt\"\x8b\x01\n" +
	"\rServingStatus\x12\x1a\n" +
	"\x16SERVING_STATUS_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16SERVING_STATUS_SERVING\x10\x01\x12\x1e\n" +
	"\x1aSERVING_STATUS_NOT_SERVING\x10\x02\x12\"\n" +
	"\x1eSERVING_STATUS_SERVICE_UNKNOWN\x10\x03*s\n" +
	"\vMessageRole\x12\x1c\n" +
	"\x18MESSAGE_ROLE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_ROLE_USER\x10\x01\x12\x16\n" +
	"\x12MESSAGE_ROLE_AGENT\x10\x02\x12\x17\n" +
	"\x13MESSAGE_ROLE_SYSTEM\x10\x03*a\n" +
	"\bPartKind\x12\x19\n" +
	"\x15PART_KIND_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePART_KIND_TEXT\x10\x01\x12\x12\n" +
	"\x0ePART_KIND_FILE\x10\x02\x12\x12\n" +
	"\x0ePART_KIND_DATA\x10\x032\xe4\x02\n" +
	"\fAgentService\x12P\n" +
	"\vSendMessage\x12\x1f.sage.adk.v1.SendMessageRequest\x1a .sage.adk.v1.SendMessageResponse\x12[\n" +
	"\x0eStreamMessages\x12!.sage.adk.v1.StreamMessageRequest\x1a\".sage.adk.v1.StreamMessageResponse(\x010\x01\x12S\n" +
	"\fGetAgentInfo\x12 .sage.adk.v1.GetAgentInfoRequest\x1a!.sage.adk.v1.GetAgentInfoResponse\x12P\n" +
	"\vHealthCheck\x12\x1f.sage.adk.v1.HealthCheckRequest\x1a .sage.adk.v1.HealthCheckResponseB0Z.github.com/sage-x-project/sage-adk/proto/pb;pbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_agent_proto_goTypes = []any{
	(MessageRole)(0),                       // 0: sage.adk.v1.MessageRole
	(PartKind)(0),                          // 1: sage.adk.v1.PartKind
	(StreamControl_ControlType)(0),         // 2: sage.adk.v1.StreamControl.ControlType
	(StreamStatus_StatusType)(0),           // 3: sage.adk.v1.StreamStatus.StatusType
	(HealthCheckResponse_ServingStatus)(0), // 4: sage.adk.v1.HealthCheckResponse.ServingStatus
	(*TextPart)(nil),                       // 5: sage.adk.v1.TextPart
	(*FileContent)(nil),                    // 6: sage.adk.v1.FileContent
	(*FileWithBytes)(nil),                  // 7: sage.adk.v1.FileWithBytes
	(*FileWithURI)(nil),                    // 8: sage.adk.v1.FileWithURI
	(*FilePart)(nil),                       // 9: sage.adk.v1.FilePart
	(*DataPart)(nil),                       // 10: sage.adk.v1.DataPart
	(*Part)(nil),                           // 11: sage.adk.v1.Part
	(*Message)(nil),                        // 12: sage.adk.v1.Message
	(*SendMessageRequest)(nil),             // 13: sage.adk.v1.SendMessageRequest
	(*SendMessageResponse)(nil),            // 14: sage.adk.v1.SendMessageResponse
	(*StreamMessageRequest)(nil),           // 15: sage.adk.v1.StreamMessageRequest
	(*StreamControl)(nil),                  // 16: sage.adk.v1.StreamControl
	(*StreamMessageResponse)(nil),          // 17: sage.adk.v1.StreamMessageResponse
	(*StreamStatus)(nil),                   // 18: sage.adk.v1.StreamStatus
	(*GetAgentInfoRequest)(nil),            // 19: sage.adk.v1.GetAgentInfoRequest
	(*GetAgentInfoResponse)(nil),           // 20: sage.adk.v1.GetAgentInfoResponse
	(*AgentCard)(nil),                      // 21: sage.adk.v1.AgentCard
	(*HealthCheckRequest)(nil),             // 22: sage.adk.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 23: sage.adk.v1.HealthCheckResponse
	(*structpb.Struct)(nil),                // 24: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),          // 25: google.protobuf.Timestamp
}
var file_agent_proto_depIdxs = []int32{
	24, // 0: sage.adk.v1.TextPart.metadata:type_name -> google.protobuf.Struct
	7,  // 1: sage.adk.v1.FileContent.bytes:type_name -> sage.adk.v1.FileWithBytes
	8,  // 2: sage.adk.v1.FileContent.uri:type_name -> sage.adk.v1.FileWithURI
	6,  // 3: sage.adk.v1.FilePart.file:type_name -> sage.adk.v1.FileContent
	24, // 4: sage.adk.v1.FilePart.metadata:type_name -> google.protobuf.Struct
	24, // 5: sage.adk.v1.DataPart.data:type_name -> google.protobuf.Struct
	24, // 6: sage.adk.v1.DataPart.metadata:type_name -> google.protobuf.Struct
	5,  // 7: sage.adk.v1.Part.text:type_name -> sage.adk.v1.TextPart
	9,  // 8: sage.adk.v1.Part.file:type_name -> sage.adk.v1.FilePart
	10, // 9: sage.adk.v1.Part.data:type_name -> sage.adk.v1.DataPart
	0,  // 10: sage.adk.v1.Message.role:type_name -> sage.adk.v1.MessageRole
	11, // 11: sage.adk.v1.Message.parts:type_name -> sage.adk.v1.Part
	24, // 12: sage.adk.v1.Message.metadata:type_name -> google.protobuf.Struct
	25, // 13: sage.adk.v1.Message.created_at:type_name -> google.protobuf.Timestamp
	25, // 14: sage.adk.v1.Message.updated_at:type_name -> google.protobuf.Timestamp
	12, // 15: sage.adk.v1.SendMessageRequest.message:type_name -> sage.adk.v1.Message
	12, // 16: sage.adk.v1.SendMessageResponse.message:type_name -> sage.adk.v1.Message
	25, // 17: sage.adk.v1.SendMessageResponse.processed_at:type_name -> google.protobuf.Timestamp
	12, // 18: sage.adk.v1.StreamMessageRequest.message:type_name -> sage.adk.v1.Message
	16, // 19: sage.adk.v1.StreamMessageRequest.control:type_name -> sage.adk.v1.StreamControl
	2,  // 20: sage.adk.v1.StreamControl.type:type_name -> sage.adk.v1.StreamControl.ControlType
	24, // 21: sage.adk.v1.StreamControl.data:type_name -> google.protobuf.Struct
	12, // 22: sage.adk.v1.StreamMessageResponse.message:type_name -> sage.adk.v1.Message
	18, // 23: sage.adk.v1.StreamMessageResponse.status:type_name -> sage.adk.v1.StreamStatus
	3,  // 24: sage.adk.v1.StreamStatus.type:type_name -> sage.adk.v1.StreamStatus.StatusType
	25, // 25: sage.adk.v1.StreamStatus.timestamp:type_name -> google.protobuf.Timestamp
	21, // 26: sage.adk.v1.GetAgentInfoResponse.agent_card:type_name -> sage.adk.v1.AgentCard
	24, // 27: sage.adk.v1.AgentCard.metadata:type_name -> google.protobuf.Struct
	4,  // 28: sage.adk.v1.HealthCheckResponse.status:type_name -> sage.adk.v1.HealthCheckResponse.ServingStatus
	25, // 29: sage.adk.v1.HealthCheckResponse.checked_at:type_name -> google.protobuf.Timestamp
	13, // 30: sage.adk.v1.AgentService.SendMessage:input_type -> sage.adk.v1.SendMessageRequest
	15, // 31: sage.adk.v1.AgentService.StreamMessages:input_type -> sage.adk.v1.StreamMessageRequest
	19, // 32: sage.adk.v1.AgentService.GetAgentInfo:input_type -> sage.adk.v1.GetAgentInfoRequest
	22, // 33: sage.adk.v1.AgentService.HealthCheck:input_type -> sage.adk.v1.HealthCheckRequest
	14, // 34: sage.adk.v1.AgentService.SendMessage:output_type -> sage.adk.v1.SendMessageResponse
	17, // 35: sage.adk.v1.AgentService.StreamMessages:output_type -> sage.adk.v1.StreamMessageResponse
	20, // 36: sage.adk.v1.AgentService.GetAgentInfo:output_type -> sage.adk.v1.GetAgentInfoResponse
	23, // 37: sage.adk.v1.AgentService.HealthCheck:output_type -> sage.adk.v1.HealthCheckResponse
	34, // [34:38] is the sub-list for method output_type
	30, // [30:34] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*FileContent_Bytes)(nil),
		(*FileContent_Uri)(nil),
	}
	file_agent_proto_msgTypes[6].OneofWrappers = []any{
		(*Part_Text)(nil),
		(*Part_File)(nil),
		(*Part_Data)(nil),
	}
	file_agent_proto_msgTypes[10].OneofWrappers = []any{
		(*StreamMessageRequest_Message)(nil),
		(*StreamMessageRequest_Control)(nil),
	}
	file_agent_proto_msgTypes[12].OneofWrappers = []any{
		(*StreamMessageResponse_Message)(nil),
		(*StreamMessageResponse_Status)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
